version: '3.3'
services:
  eureka-server:
    build: eureka/
    tty: true
    ports:
      - "9997:9997"

  gateway-service:
    build: gateway/
    tty: true
    ports:
      - "9998:9998"
    depends_on:
      - eureka-server

  admin-service:
    build: admin/
    tty: true
    ports:
      - "9999:9999"
    depends_on:
      - eureka-server

  user-service:
    build: users/
    tty: true
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server