version: '3.3'

networks:
  cc_backend_network:
    driver: bridge

services:
  eureka-server:
    build: eureka/
    tty: true
    ports:
      - "9997:9997"
    networks:
      - cc_backend_network
    container_name: eureka-server
    image: adechauveron/chefchallenge-eureka

  gateway-service:
    build: gateway/
    tty: true
    ports:
      - "9998:9998"
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://eureka-server:9997/eureka"}}}}'
    depends_on:
      - eureka-server
    networks:
      - cc_backend_network
    container_name: gateway-service
    image: adechauveron/chefchallenge-gateway

  admin-service:
    build: admin/
    tty: true
    ports:
      - "9999:9999"
    depends_on:
      - eureka-server
      - gateway-service
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://eureka-server:9997/eureka"}}}}'
    networks:
      - cc_backend_network
    container_name: admin-service
    image: adechauveron/chefchallenge-admin

  user-service:
    build: users/
    tty: true
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - gateway-service
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://eureka-server:9997/eureka"}}}}'
    networks:
      - cc_backend_network
    container_name: user-service
    image: adechauveron/chefchallenge-user

  ingredient-service:
    build: ingredients/
    tty: true
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - gateway-service
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://eureka-server:9997/eureka"}}}}'
    networks:
      - cc_backend_network
    container_name: ingredients-service
    image: adechauveron/chefchallenge-ingredient


  challenge-service:
    build: challenges/
    tty: true
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
      - gateway-service
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://eureka-server:9997/eureka"}}}}'
    networks:
      - cc_backend_network
    container_name: challenge-service
    image: adechauveron/chefchallenge-challenge

  recipe-service:
    build: recipes/
    tty: true
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - gateway-service
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://eureka-server:9997/eureka"}}}}'
    networks:
      - cc_backend_network
    container_name: recipe-service
    image: adechauveron/chefchallenge-recipe

  stock-service:
    build: stock/
    tty: true
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - gateway-service
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://eureka-server:9997/eureka"}}}}'
    networks:
      - cc_backend_network
    container_name: stock-service
    image: adechauveron/chefchallenge-stock
