version: 2

jobs:
  build: &shared-config
    docker:
      - image: circleci/openjdk:11-buster-node-browsers-legacy

    steps:
      - checkout
      - run:
          name: Install all dependencies
          command: |
              for SERVICE in admin challenges eureka gateway ingredients recipes stock users
              do
                echo "Installing dependencies for service ${SERVICE}"
                cd ${SERVICE} && ./mvnw clean install && ./mvnw package && cd ..
              done

  docker-build-and-push:
    docker:
      - image: circleci/openjdk:11-buster-node-browsers-legacy
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: '1.29.2'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build application Docker image
          command: docker-compose build
      - deploy:
          name: Publish application to docker hub
          command: |
            docker login -e $PROD_EMAIL -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker tag app $DOCKERHUB_USERNAME/$DOCKERHUB_APP_NAME:$CIRCLE_BUILD_NUM
            docker tag app $DOCKERHUB_USERNAME/$DOCKERHUB_APP_NAME:latest
            docker-compose push $DOCKERHUB_USERNAME/$DOCKERHUB_APP_NAME:$CIRCLE_BUILD_NUM
            docker-compose push $DOCKERHUB_USERNAME/$DOCKERHUB_APP_NAME:latest


workflows:
  version: 2
  continuous_integration:
    jobs:
      - build
      - docker-build-and-push:
          requires:
            - build
          filters:
            branches:
              only: master